Feature/65 add map to the search page
lat-02-mobile/lat02-routes-ios pull request #10
Opened 2022-08-20 20:34 UTC by jimibilibob

2022-08-22 18:18 UTC, YawarValeriano requested changes

2022-08-22 18:18 UTC, YawarValeriano commented on RoutesApp_ios/modules/home/controllers/HomeViewController.swift
> +            print("Authorize.")
Avoid using prints

2022-08-22 18:18 UTC, YawarValeriano commented on RoutesApp_ios/modules/home/controllers/HomeViewController.swift
> +        print("error:: \(error.localizedDescription)")
same here about print

2022-08-22 18:37 UTC, jimibilibob commented on RoutesApp_ios/modules/home/controllers/HomeViewController.swift
> +        print("error:: \(error.localizedDescription)")
Removed

2022-08-22 18:37 UTC, jimibilibob commented on RoutesApp_ios/modules/home/controllers/HomeViewController.swift
> +            print("Authorize.")
All prints removed

2022-08-22 19:28 UTC, YawarValeriano approved these changes

2022-08-23 14:15 UTC, jmacboy approved these changes

2022-08-23 22:13 UTC, merged