Feature/72 city picker for new user
lat-02-mobile/lat02-routes-ios pull request #12
Opened 2022-08-26 20:43 UTC by Rodrigo-Schar

- added city picker
- added city picker for settings and launcher
- fixed get country model
- merge develop
- added change map based on city
- added cities list and fix design
- added UnitTest and corrections

2022-08-29 15:00 UTC, jimibilibob commented on RoutesApp_ios/modules/citypicker/controllers/CityPickerViewController.swift
> +import SwiftUI
Why are you using SwiftUI?

2022-08-29 18:12 UTC, Rodrigo-Schar commented on RoutesApp_ios/modules/citypicker/controllers/CityPickerViewController.swift
> +import SwiftUI
import removed!

2022-09-01 02:06 UTC, jmacboy requested changes

2022-09-01 02:06 UTC, jmacboy commented on RoutesApp_ios/Assets.xcassets/Icons/arrow-left-primary.imageset/Contents.json
> +      "filename" : "Arrow 1.svg",
use more descriptive names for your files, Arrow 1.svg should be arrow-left-primary.svg

2022-09-01 02:06 UTC, jmacboy commented on RoutesApp_ios/Assets.xcassets/Icons/arrow-right.imageset/Contents.json
> +      "filename" : "Arrow 5.svg",
same for filename here

2022-09-01 02:06 UTC, jmacboy commented on RoutesApp_ios/Assets.xcassets/Images/city-picker-background.imageset/Contents.json
> +      "filename" : "image 7.svg",
also the name of this image

2022-09-01 02:06 UTC, jmacboy commented on RoutesApp_ios/Assets.xcassets/Images/city-picker-emoji.imageset/Contents.json
> +      "filename" : "exito (2) 1.png",
and this one

2022-09-01 02:06 UTC, jmacboy commented on RoutesApp_ios/Assets.xcassets/Images/city-picker-world.imageset/Contents.json
> +      "filename" : "image 5.svg",
also this one

2022-09-01 14:11 UTC, jmacboy approved these changes

2022-09-01 14:18 UTC, jimibilibob approved these changes

2022-09-01 14:20 UTC, merged